version: '3.8'

services: 
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: amitlks
      POSTGRES_PASSWORD: amit555
      POSTGRES_DB: blogDB
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
