name = "backend"
main = "src/index.ts"

compatibility_date = "2026-09-17"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "blogweb-backend"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "5b6bd14c7fc34a8ebd7ca5dc2171848b"
localConnectionString = "postgresql://amitlks:amit555@localhost:5434/blogDB?schema=public"

# MY_VAR = "my-variable"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"